apiVersion: v1
kind: ConfigMap
metadata:
  name: configfile
data:
  DB_HOST: mariadb
  DB_PORT: "3306"
  DB_NAME: cv
  DB_USER: cvuser
  init.sql: |
    CREATE TABLE IF NOT EXISTS counter (
      id INT PRIMARY KEY,
      views INT
    );

    INSERT IGNORE INTO counter (id, views)
    VALUES (1, 0);
