name: App deploy

on:
  push:
    branches: [ main ]
    paths:
      - app/flask/**
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r app/flask/requirements.txt
          pip install flake8 pylint==3.0.3 astroid==3.0.3

      - name: Start services
        run: docker compose up -d --build
        working-directory: app

      - name: Run app test
        run: |
          pip install requests
          sleep 5
          python test_app.py
        working-directory: app/flask
        env:
          TARGET_URL: http://localhost:5000/view

      - name: Stop services
        if: always()
        run: docker compose down
        working-directory: app

      - name: flake8 (style check)
        run: flake8 .
        working-directory: app/flask

      - name: pylint (static analysis report)
        run: |
          pylint app.py --output-format=parseable > pylint-report.txt || true
          echo "===== PYLINT REPORT ====="
          cat pylint-report.txt          
        working-directory: app/flask

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@v2
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.projectKey=resume-action073191_resume-app
      #       -Dsonar.organization=resume-action073191
      #       -Dsonar.sources=app/flask
      #       -Dsonar.python.version=3.11
      #       -Dsonar.python.pylint.reportPaths=app/flask/pylint-report.txt

      # - name: SonarCloud Quality Gate
      #   uses: SonarSource/sonarqube-quality-gate-action@v1
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
