name: App deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  AWS_REGION: us-east-2
  ECR_REPO_FLASK: resume-flask
  ECR_REPO_NGINX: resume-nginx
  EKS_CLUSTER: resume-eks

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r app/flask/requirements.txt
          pip install flake8 pylint==3.0.3 astroid==3.0.3

      - name: Start services
        run: docker compose up -d --build
        working-directory: app

      - name: Run app test
        run: |
          pip install requests
          sleep 5
          python test_app.py
        working-directory: app/flask
        env:
          TARGET_URL: http://localhost:5000/view

      - name: Stop services
        if: always()
        run: docker compose down
        working-directory: app

      - name: flake8 (style check)
        run: flake8 .
        working-directory: app/flask

      - name: pylint (static analysis report)
        run: |
          pylint app.py --output-format=parseable > pylint-report.txt || true
          echo "===== PYLINT REPORT ====="
          cat pylint-report.txt          
        working-directory: app/flask

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@v2
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.projectKey=resume-action073191_resume-app
      #       -Dsonar.organization=resume-action073191
      #       -Dsonar.sources=app/flask
      #       -Dsonar.python.version=3.11
      #       -Dsonar.python.pylint.reportPaths=app/flask/pylint-report.txt

      # - name: SonarCloud Quality Gate
      #   uses: SonarSource/sonarqube-quality-gate-action@v1
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-publish:
    needs: testing
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push Flask
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_FLASK }}:$TAG app/flask
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_FLASK }}:$TAG

      - name: Build & push Nginx
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NGINX }}:$TAG app/nginx
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NGINX }}:$TAG    

  deploy-to-EKS:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4    

      - name: Set image tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Kube config file
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Deploy Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          cluster-name: ${{ env.EKS_CLUSTER }}
          chart-path: helm-chart
          namespace: default
          name: flask-nginx-mariadb
          values: image.flask.repository=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_FLASK }},image.flask.tag=${{ env.TAG }},image.nginx.repository=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_NGINX }},image.nginx.tag=${{ env.TAG }}


